version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auditdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  audit-service:
    build: .
    depends_on:
      - db
    ports:
      - '3003:3003'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/auditdb
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
